general:
  root_path: ../../vnncomp2021/benchmarks/marabou-cifar10 # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: marabou-cifar10_instances.csv
model:
  # Use the function customized_Marabou_loader() in custom_model_loader.py to load this model.
  onnx_loader: Customized("custom_model_loader", "customized_Marabou_loader")
data:
  start: 48
  end: 49
solver:
  batch_size: 512
