model:
  name: mnist64fc
  path: models/custom/mnist_fc_64x4_adv_1.model
data:
  dataset: MNIST
  start: 0
  end: 20
  std: [1.]
  mean: [0.]
specification:
  epsilon: 0.2
  norm: .inf
attack:
  pgd_order: after
solver:
  batch_size: 4096
bab:
  timeout: 500
