model:
  name: mnist64fc
  path: models/custom/64x4_scratch.model
data:
  dataset: MNIST
  start: 0
  end: 10
  std: [1.]
  mean: [0.]
specification:
  epsilon: 0.05
  norm: .inf
attack:
  pgd_order: skip
solver:
  batch_size: 4096
bab:
  timeout: 180
